### ISSUE TITLE
Some hydra outputs crash `,.eval-report`

### ISSUE THREAD

**Issue by trofi** [nix-community/nix-review-tools#13]
Today's crash:

```
$ ./eval-report 1704065
...
Downloading https://hydra.nixos.org/build/152619227...
Parsing build_152619227
Traceback (most recent call last):
	10: from -e:1:in `<main>'
	 9: from -e:1:in `load'
	 8: from /home/slyfox/dev/git/nix-review-tools/eval-report:16:in `<top (required)>'
	 7: from /home/slyfox/dev/git/nix-review-tools/eval-report:16:in `map'
	 6: from /home/slyfox/dev/git/nix-review-tools/eval-report:16:in `block in <top (required)>'
	 5: from /home/slyfox/dev/git/nix-review-tools/lib/hydra/eval.rb:20:in `get'
	 4: from /home/slyfox/dev/git/nix-review-tools/lib/hydra/eval.rb:20:in `map'
	 3: from /home/slyfox/dev/git/nix-review-tools/lib/hydra/eval.rb:37:in `block in get'
	 2: from /home/slyfox/dev/git/nix-review-tools/lib/hydra/eval.rb:37:in `tap'
	 1: from /home/slyfox/dev/git/nix-review-tools/lib/hydra/eval.rb:39:in `block (2 levels) in get'
/home/slyfox/dev/git/nix-review-tools/lib/hydra/build.rb:19:in `get': undefined method `next_element' for nil:NilClass (NoMethodError)
```

**Comment by trofi** [comment]
Attaching the file: [build_152619227.txt](https://github.com/nix-community/nix-review-tools/files/7152826/build_152619227.txt)

**Comment by vcunat** [comment]
Also here: https://github.com/malob/nix-review-tools-reports/actions/runs/7691838593/job/20957835063#step:6:11630
